# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wol1KVSVzciUymboE3kW3fkcx4Z5Ufjf
"""

# Import required libraries
import pandas as pd

# Path to dataset
file_path = "/content/BI_Chatbot_Interactions.csv"

# Read dataset
df = pd.read_csv(file_path)

# Display basic dataset information
print("Dataset Loaded Successfully\n")

# Shape of dataset
print("Dataset Shape (Rows, Columns):", df.shape)
print("\n")

# Display first 5 rows
print("First 5 Rows of Dataset:")
display(df.head())
print("\n")

# Display all column names
print("Column Names:")
print(df.columns.tolist())
print("\n")

# Display data types
print("Data Types of Columns:")
print(df.dtypes)
print("\n")

# Check missing values
print("Missing Values in Each Column:")
print(df.isnull().sum())

# ===============================
# DATA CLEANING & PREPROCESSING
# ===============================

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

# Make a copy of original dataset
df_clean = df.copy()

print("Initial Dataset Shape:", df_clean.shape)
print("--------------------------------------------------")

# 1️ Convert timestamp to datetime
df_clean['timestamp'] = pd.to_datetime(df_clean['timestamp'])

# Extract useful time features
df_clean['year'] = df_clean['timestamp'].dt.year
df_clean['month'] = df_clean['timestamp'].dt.month
df_clean['day'] = df_clean['timestamp'].dt.day
df_clean['hour'] = df_clean['timestamp'].dt.hour

print("Timestamp converted and new time features created.")
print("--------------------------------------------------")

# 2️ Handle Missing Values

# Fill missing user feedback with median
df_clean['user_feedback_rating'].fillna(df_clean['user_feedback_rating'].median(), inplace=True)

# Fill missing business impact with 'Unknown'
df_clean['estimated_business_impact'].fillna('Unknown', inplace=True)

print("Missing values handled.")
print("--------------------------------------------------")

# 3️ Remove duplicate rows (if any)
duplicates = df_clean.duplicated().sum()
df_clean = df_clean.drop_duplicates()

print("Duplicates Removed:", duplicates)
print("--------------------------------------------------")

# 4️ Standardize text columns (lowercase + strip spaces)
text_columns = [
    'department',
    'user_role',
    'query_category',
    'metrics_requested',
    'analysis_type',
    'estimated_business_impact'
]

for col in text_columns:
    df_clean[col] = df_clean[col].str.strip().str.lower()

print("Text columns standardized.")
print("--------------------------------------------------")

# 5️ Encode categorical columns for ML
label_encoders = {}

categorical_cols = [
    'department',
    'user_role',
    'query_category',
    'metrics_requested',
    'analysis_type',
    'estimated_business_impact'
]

for col in categorical_cols:
    le = LabelEncoder()
    df_clean[col + "_encoded"] = le.fit_transform(df_clean[col])
    label_encoders[col] = le

print("Categorical columns encoded.")
print("--------------------------------------------------")

# 6️ Create performance indicator features

# Response speed category
df_clean['response_speed'] = np.where(df_clean['response_time_ms'] < 1000, 'fast',
                         np.where(df_clean['response_time_ms'] < 2000, 'moderate', 'slow'))

# Satisfaction indicator
df_clean['high_satisfaction'] = np.where(df_clean['user_feedback_rating'] >= 4, 1, 0)

print("New analytical features created.")
print("--------------------------------------------------")

# 7️ Final dataset overview
print("Cleaned Dataset Shape:", df_clean.shape)
print("\nFinal Columns:")
print(df_clean.columns.tolist())

print("\nSample Cleaned Data:")
display(df_clean.head())

# ==========================================
# EXPLORATORY DATA ANALYSIS (EDA)
# ==========================================

import matplotlib.pyplot as plt
import seaborn as sns

print("EDA STARTED")
print("Dataset Shape:", df_clean.shape)

# ------------------------------------------
# 1️ Summary Statistics
# ------------------------------------------
print("\nSummary Statistics:")
display(df_clean.describe())

# ------------------------------------------
# 2️ Department Distribution
# ------------------------------------------
plt.figure()
df_clean['department'].value_counts().plot(kind='bar')
plt.title("Department Distribution")
plt.xlabel("Department")
plt.ylabel("Count")
plt.show()

# ------------------------------------------
# 3️ Query Category Distribution
# ------------------------------------------
plt.figure()
df_clean['query_category'].value_counts().plot(kind='bar')
plt.title("Query Category Distribution")
plt.xlabel("Query Category")
plt.ylabel("Count")
plt.show()

# ------------------------------------------
# 4️ Analysis Type Distribution
# ------------------------------------------
plt.figure()
df_clean['analysis_type'].value_counts().plot(kind='bar')
plt.title("Analysis Type Distribution")
plt.xlabel("Analysis Type")
plt.ylabel("Count")
plt.show()

# ------------------------------------------
# 5️ Response Time Distribution
# ------------------------------------------
plt.figure()
plt.hist(df_clean['response_time_ms'], bins=30)
plt.title("Response Time Distribution")
plt.xlabel("Response Time (ms)")
plt.ylabel("Frequency")
plt.show()

# ------------------------------------------
# 6 Bot Confidence Distribution
# ------------------------------------------
plt.figure()
plt.hist(df_clean['bot_response_confidence'], bins=30)
plt.title("Bot Response Confidence Distribution")
plt.xlabel("Confidence Score")
plt.ylabel("Frequency")
plt.show()

# ------------------------------------------
# 7️ User Feedback Rating Distribution
# ------------------------------------------
plt.figure()
plt.hist(df_clean['user_feedback_rating'], bins=10)
plt.title("User Feedback Rating Distribution")
plt.xlabel("Feedback Rating")
plt.ylabel("Count")
plt.show()

# ------------------------------------------
# 8️ Business Impact Distribution
# ------------------------------------------
plt.figure()
df_clean['estimated_business_impact'].value_counts().plot(kind='bar')
plt.title("Estimated Business Impact")
plt.xlabel("Impact Level")
plt.ylabel("Count")
plt.show()

# ------------------------------------------
# 9️ Department vs Feedback Rating
# ------------------------------------------
plt.figure()
sns.boxplot(x=df_clean['department'], y=df_clean['user_feedback_rating'])
plt.title("Feedback Rating by Department")
plt.show()

# ------------------------------------------
#  Response Time vs Feedback
# ------------------------------------------
plt.figure()
sns.scatterplot(x=df_clean['response_time_ms'], y=df_clean['user_feedback_rating'])
plt.title("Response Time vs User Feedback")
plt.xlabel("Response Time (ms)")
plt.ylabel("User Feedback Rating")
plt.show()

# ------------------------------------------
# 11️ Correlation Heatmap
# ------------------------------------------
numeric_cols = [
    'bot_response_confidence',
    'response_time_ms',
    'user_feedback_rating',
    'department_encoded',
    'user_role_encoded',
    'query_category_encoded',
    'metrics_requested_encoded',
    'analysis_type_encoded',
    'estimated_business_impact_encoded'
]

plt.figure()
sns.heatmap(df_clean[numeric_cols].corr(), annot=True)
plt.title("Correlation Heatmap")
plt.show()

print("\nEDA COMPLETED")

# ==========================================
# MACHINE LEARNING PIPELINE
# ==========================================

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

print("Machine Learning Pipeline Started")

# ------------------------------------------
# 1️⃣ Feature Selection
# ------------------------------------------

features = [
    'bot_response_confidence',
    'response_time_ms',
    'department_encoded',
    'user_role_encoded',
    'query_category_encoded',
    'metrics_requested_encoded',
    'analysis_type_encoded',
    'estimated_business_impact_encoded',
    'hour',
    'month'
]

X = df_clean[features]
y = df_clean['high_satisfaction']

print("Features Selected:", features)

# ------------------------------------------
# 2️⃣ Train Test Split
# ------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Train Shape:", X_train.shape)
print("Test Shape:", X_test.shape)

# ------------------------------------------
# 3️⃣ Train Models
# ------------------------------------------

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier()
}

results = {}

for name, model in models.items():

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)

    results[name] = acc

    print("\n===================================")
    print(name)
    print("Accuracy:", acc)
    print("\nClassification Report:\n")
    print(classification_report(y_test, y_pred))

# ------------------------------------------
# 4️⃣ Best Model
# ------------------------------------------

best_model_name = max(results, key=results.get)
print("\nBest Model:", best_model_name)

best_model = models[best_model_name]

# ------------------------------------------
# 5️⃣ Confusion Matrix
# ------------------------------------------

y_pred = best_model.predict(X_test)

plt.figure()
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# ------------------------------------------
# 6️⃣ Feature Importance (Random Forest)
# ------------------------------------------

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

importance = rf.feature_importances_

plt.figure()
plt.barh(features, importance)
plt.title("Feature Importance")
plt.show()

# ------------------------------------------
# 7️⃣ Example Prediction
# ------------------------------------------

sample = X_test.iloc[0:1]

prediction = best_model.predict(sample)

print("\nSample Prediction:", prediction)

print("\nMachine Learning Pipeline Completed")

# ==========================================
# ADDITIONAL DATA VISUALIZATION (10 GRAPHS)
# ==========================================

import matplotlib.pyplot as plt
import seaborn as sns

print("Generating Additional Visualizations")

# ------------------------------------------
# 1️⃣ Department vs Satisfaction
# ------------------------------------------
plt.figure()
sns.countplot(x='department', hue='high_satisfaction', data=df_clean)
plt.title("Department vs User Satisfaction")
plt.xticks(rotation=45)
plt.show()

# ------------------------------------------
# 2️⃣ Query Category vs Satisfaction
# ------------------------------------------
plt.figure()
sns.countplot(x='query_category', hue='high_satisfaction', data=df_clean)
plt.title("Query Category vs Satisfaction")
plt.xticks(rotation=45)
plt.show()

# ------------------------------------------
# 3️⃣ Response Time by Department
# ------------------------------------------
plt.figure()
sns.boxplot(x='department', y='response_time_ms', data=df_clean)
plt.title("Response Time by Department")
plt.xticks(rotation=45)
plt.show()

# ------------------------------------------
# 4️⃣ Bot Confidence vs Feedback
# ------------------------------------------
plt.figure()
sns.scatterplot(x='bot_response_confidence', y='user_feedback_rating', data=df_clean)
plt.title("Bot Confidence vs User Feedback")
plt.show()

# ------------------------------------------
# 5️⃣ Analysis Type Distribution
# ------------------------------------------
plt.figure()
sns.countplot(x='analysis_type', data=df_clean)
plt.title("Analysis Type Distribution")
plt.xticks(rotation=45)
plt.show()

# ------------------------------------------
# 6️⃣ Response Speed Distribution
# ------------------------------------------
plt.figure()
sns.countplot(x='response_speed', data=df_clean)
plt.title("Response Speed Category")
plt.show()

# ------------------------------------------
# 7️⃣ Hourly Interaction Trend
# ------------------------------------------
plt.figure()
sns.lineplot(x='hour', y='bot_response_confidence', data=df_clean)
plt.title("Average Bot Confidence by Hour")
plt.show()

# ------------------------------------------
# 8️⃣ Monthly Interaction Trend
# ------------------------------------------
plt.figure()
sns.lineplot(x='month', y='user_feedback_rating', data=df_clean)
plt.title("Average Feedback by Month")
plt.show()

# ------------------------------------------
# 9️⃣ Business Impact vs Satisfaction
# ------------------------------------------
plt.figure()
sns.countplot(x='estimated_business_impact', hue='high_satisfaction', data=df_clean)
plt.title("Business Impact vs User Satisfaction")
plt.xticks(rotation=45)
plt.show()

# ------------------------------------------
# 🔟 Feature Importance (Random Forest)
# ------------------------------------------
features = [
    'bot_response_confidence',
    'response_time_ms',
    'department_encoded',
    'user_role_encoded',
    'query_category_encoded',
    'metrics_requested_encoded',
    'analysis_type_encoded',
    'estimated_business_impact_encoded',
    'hour',
    'month'
]

importance = rf.feature_importances_

plt.figure()
sns.barplot(x=importance, y=features)
plt.title("Feature Importance (Random Forest)")
plt.show()

print("All Visualizations Generated Successfully")